//
//  allSpeciesBDD.swift
//  GeodexPrototype
//
//  Created by Amandine LEFEBVRE on 01/07/2020.
//  Copyright © 2020 Amandine LEFEBVRE. All rights reserved.
//

import Foundation

var selectedRegion = EnumRegion.france
var selectedCategory = CategorySpecies.all

let allSpecies: [Species] = [
    
    //Birds - 0
    Species(picture: "hibou_des_marais", picture2: nil, picture3: nil, name: "Hibou des marais", latinName: "Asio flammeus", isProtected: true, isReglemented: true, isThreatened: true, category: [CategorySpecies.birds, CategorySpecies.all], description: "aussi grand que le Hibou moyen-duc, sa tête porte des aigrettes peu visibles faites de plumes allongées. Ses yeux jaunes sont cernés de noir et entourés de disques faciaux blancs. Son plumage est brun à jaune-roux rayé de brun-noir sur le dessus, tandis que des flammèches sombres parsèment le poitrail. Ses ailes sont assez longues et sa queue courte.", habitat:"espaces découverts et sauvages, comme les prairies herbeuses, les terrains cultivés, les marais salants, les estuaires, les prairies montagneuses et la toundra alpine et arctique.", biology: "nourriture est presque essentiellement constituée de campagnols (à 90 %) puis de petits rats et de souris, rarement d'oiseaux, de lézards et serpents parfois de quelques insectes." , mainColor: [ColorChoice.brown], secondaryColor: [ColorChoice.black, ColorChoice.white, ColorChoice.yellow], bodyCover: BodyCover.plume, minSize: 37, maxSize: 107, isShared: nil, isPin: false, isPin2: false, isPin3: true,localisation: [EnumRegion.bretagne, EnumRegion.france]),
    
    
    //1
    Species(picture: "harfang-1", picture2: nil, picture3: nil, name: "Harfang des neiges", latinName: "Bubo scandiacus", isProtected: true, isReglemented: true, isThreatened: true, category: [CategorySpecies.birds, CategorySpecies.all], description: "Le Harfang des neiges (Bubo scandiacus) est une espèce d'oiseau de la famille des strigidés. Il est aussi appelé ookpik par les Inuits. Il est l'emblème aviaire du Québec depuis 19871. En France, on l'appelle Chouette Harfang, même si, en réalité, il appartient au même genre Bubo que les hiboux grand-ducs. Comme ces derniers, il possède de petites plumes sur sa tête appelées aigrettes, mais très peu visibles puisqu'elles sont très petites et repliées sur sa tête.", habitat:"niche souvent à proximité des côtes et en dehors de la période de reproduction occupe des paysages ouverts situés à proximité du littoral marin.", biology: "petits mammifères comme les lemmings et les campagnols mais peuvent également chasser des oiseaux (canards, échassiers, …), des insectes, des crustacés et des poissons." , mainColor: [ColorChoice.white], secondaryColor: [ColorChoice.black, ColorChoice.yellow], bodyCover: BodyCover.plume, minSize: 160, maxSize: 170, isShared: nil, isPin: true, isPin2: false, isPin3: false,localisation: [EnumRegion.nord, EnumRegion.bretagne, EnumRegion.france]),
    
    //2
    Species(picture: "aigrette_garzette", picture2: nil, picture3: nil, name: "Aigrette garzette", latinName: "Egretta garzetta", isProtected: true, isReglemented: true, isThreatened: true, category: [CategorySpecies.birds, CategorySpecies.all], description: "En période nuptiale, elle porte sur la nuque deux longues plumes fines de 20 cm environ appelés les aigrettes.", habitat:" toutes les zones humides aux eaux peu profondes, lagunes, claires à huîtres, avec une prédilection pour les eaux saumâtres, le long des cours d'eau, les marais dans certaines régions.", biology: "se nourrit principalement de petits poissons (moins de 20 g), d'insectes aquatiques et terrestres, de crustacés, d'amphibiens, de mollusques, d'araignées, de vers, de reptiles et de petits oiseaux." , mainColor: [ColorChoice.white], secondaryColor: [ColorChoice.black, ColorChoice.grey], bodyCover: BodyCover.plume, minSize: 55, maxSize: 65, isShared: nil, isPin: true, isPin2: false, isPin3: false, localisation: [EnumRegion.france, EnumRegion.bretagne]),
    
    
    
    //Plants -3
    Species(picture:"Calendula_arvensis", picture2: nil, picture3: nil, name: "Souci des champs", latinName: "Calendula arvensis", isProtected: false, isReglemented: false, isThreatened: false, category: [CategorySpecies.plants, CategorySpecies.all], description: "Est une plante de petite taille que produise des fleurs jeunes de diametre entre 15 et 30.", habitat: "En France, elle est rencontrée dans les champs et les vignes de la region sud. Elle est présent aussi en Afrique du Nord, en Asie mineure et dans une grande partie de l'Europe", biology: "Leur feuilles sont velues et en forme de lance. La fleurison se derroule entre les mois de avril et décembre", mainColor: [ColorChoice.green], secondaryColor: [ColorChoice.yellow, ColorChoice.orange], bodyCover: nil, minSize: 10, maxSize: 30, isShared: nil, isPin: false, isPin2: false, isPin3: false,localisation: [EnumRegion.nord, EnumRegion.france]),
    //4
    Species(picture: "Adonis_aestivalis", picture2: nil, picture3: nil, name: "Adonis d'été", latinName: "Adonis aestivalis", isProtected: true, isReglemented: true, isThreatened: false, category: [CategorySpecies.plants, CategorySpecies.all], description: "Plante petite que pousse communément dans les cultures et que produise des fleurs rouges de centre noir. Suite a l’utilization des herbicides,  il est devenu rare et peuvent être classé comme espèce menacé si des mesures pour augmenter leur population ne sont pas mises en action. ", habitat: "Cette plante se distribues dans la region Eurasiatique.", biology: "Leur fleurs, entre 10-35 mm de diamètre, sont visibles de Mai a Août. Connu aussi comme goute de sang, a cause de la légende  de Adonis, que après être tué pour un sanglier,  avait chaque goutte de son sang transformée en une fleur par la déesse Aphrodite.", mainColor: [ColorChoice.green], secondaryColor: [ColorChoice.red], bodyCover: nil, minSize: 10, maxSize: 60, isShared: nil, isPin: false,isPin2: false, isPin3: true, localisation: [EnumRegion.nord, EnumRegion.france]),
    //5
    Species(picture: "Bellis_perennis", picture2: nil, picture3: nil, name: "Pâquerette", latinName: "Bellis perennis", isProtected: false, isReglemented: false, isThreatened: false, category: [CategorySpecies.plants, CategorySpecies.all], description: "Considère comme un grand classique de l’observation de la nature,  cette plante de taille modeste present des feuilles que comportant une seule nervure. Cela c'est un critère que la différencie d’autres espèces du même groupe.", habitat: "Bien distribué dans l’Europe caucasiene,  les pâquerettes peuvent être facilement observées dans les parcs et jardins, même au milieu de l’herbe.", biology: "Leurs fleurs mesurent entre 15-20mm et sont visibles de janvier a décembre. Ils peuvent presenter une borde rose-violet sur les pétales blanches.", mainColor: [ColorChoice.green], secondaryColor: [ColorChoice.white, ColorChoice.yellow, ColorChoice.pink], bodyCover: nil, minSize: 5, maxSize: 15, isShared: nil, isPin: false, isPin2: false, isPin3: false, localisation: [EnumRegion.nord, EnumRegion.france]),

    
    
    //Arbres
    //6
    Species(picture: "Carpinus_betulus", picture2: nil, picture3: nil,name: "Charme", latinName: "Carpinus betulus", isProtected: false, isReglemented: false, isThreatened: false, category: [CategorySpecies.trees, CategorySpecies.all], description: "Arbre de grande taille, possede feuilles dentées et avec nervures bien accentués. ", habitat: "En France cette arbre est plus facilement repère dans le Nord, mais est aussi present dans le sud (plus rare),  autres pays d’Europe et dans l’ouest Asiatique.", biology: "Plante vivace que fleurisse de avril a juin, produise des chatons de longueur entre 10-60.", mainColor: [ColorChoice.green], secondaryColor: [ColorChoice.brown], bodyCover: nil, minSize: 600, maxSize: 2500, isShared: nil, isPin: false, isPin2: false, isPin3: false, localisation: [EnumRegion.nord, EnumRegion.bretagne,EnumRegion.france]),
    
//7
    Species(picture: "Abies_alba", picture2: nil, picture3: nil,name: "Sapin pectiné", latinName: "Abies alba", isProtected: false, isReglemented: false, isThreatened: false, category: [CategorySpecies.trees, CategorySpecies.all], description: "L’écorce claire et les feuilles planes en format des aiguilles, disposées en peigne avec deux rangs opposés, son  caractéristiques marquants de cette grand arbre que peut vivre de 200 a 300 ans.", habitat: "Cette espèce a preference pour la region subalpine, et se distribue dans le continent européen.", biology: "Ses cônes, peu accessibles et disposés en haut de l'arbre, son  visibles de avril a juillet. Ils peuvent mesurer de. 10 a 15 cm .", mainColor: [ColorChoice.green], secondaryColor: [ColorChoice.brown], bodyCover: nil, minSize: 10, maxSize: 50, isShared: nil, isPin: true, isPin2: true, isPin3: false, localisation: [EnumRegion.nord, EnumRegion.france]),

//8
    Species(picture: "Betula_pendula", picture2: nil, picture3: nil, name: "Bouleau verruqueux", latinName: "Betula pendula", isProtected: false, isReglemented: false, isThreatened: false, category: [CategorySpecies.trees, CategorySpecies.all], description: "Le plus commun dans leur groupe d’arbres, le bouleau verruqueux se fait reconnaître pour ses rames verruqueux et ses feuilles triangulaires et dentées.", habitat: "Ça distribution géographique comprenne l’Europe et Asie.", biology: "Leurs chatons que mesurent entre 50 et 100 mm sont visibles pendant la floraison que va de mars a octobre.", mainColor: [ColorChoice.green], secondaryColor: [ColorChoice.brown], bodyCover: nil, minSize: 2000, maxSize: 2500, isShared: nil, isPin: false, isPin2: true, isPin3: false, localisation: [EnumRegion.nord, EnumRegion.france]),
    
    
   //9
    //Poissons et Crustacés
    Species(picture: "sandre",picture2: nil, picture3: nil, name: "Sandre", latinName: "Sander lucioperca", isProtected: false, isReglemented: true, isThreatened: false, category: [CategorySpecies.fishes, CategorySpecies.all], description: "deux nageoires dorsales distinctes, la première épineuse, la deuxième avec un ou deux rayons épineux et une vingtaine de rayons flexibles, les opercules ont deux rayons épine acérées, très coupantes sur leurs bords inférieurs. Tête assez fine et longue, gueule bien fendue, avec les deux paires de canines très développées sur les mâchoires ; un corps allongé, cylindrique et fusiforme et les lobes de la nageoire caudale nettement arrondis à leurs extrémités", habitat:"grands cours d'eau aux flots lents et aux fonds de sable ou de graviers, ainsi que les eaux calmes des lacs, étangs et réservoirs", biology: " surtout d'autres poissons de petites tailles : ablettes, goujons, petits gardons de deux ou trois ans, écrevisses.", mainColor: [ColorChoice.grey], secondaryColor: [ColorChoice.white], bodyCover: BodyCover.ecaille, minSize:30, maxSize:125, isShared: nil , isPin: false, isPin2: false, isPin3: false,localisation:[ EnumRegion.bretagne, EnumRegion.france]),

   //10
    Species(picture:"ecrevisse_pattes_blanches" , picture2: nil, picture3: nil, name: "Écrevisse à pieds blancs", latinName: "Austropotamobius pallipes", isProtected: true, isReglemented: true, isThreatened: true , category: [CategorySpecies.fishes, CategorySpecies.all], description: "distingue par la présence théorique de deux paires d'épines latérales sur le sommet de son rostre. En pratique, il est fréquent que l'une des quatre épines soit manquantes, indifféremment du côté droit ou du côté gauche. ", habitat: "eaux froides, non polluées, claires et vives, torrents et ruisseaux.", biology:"végétaux terrestres ou aquatiques. Un cannibalisme des adultes sur les jeunes existe et contribue à réguler la démographie de l'espèce." , mainColor: [ColorChoice.green], secondaryColor: [ColorChoice.red], bodyCover: BodyCover.carapace, minSize: 9, maxSize: 12, isShared: nil, isPin: true , isPin2: false, isPin3: false, localisation: [ EnumRegion.bretagne, EnumRegion.france]),

    //11
    Species(picture:"caridine", picture2: nil, picture3: nil,name:"Caridine", latinName: "Atyaephyra desmaresti", isProtected: false , isReglemented: false, isThreatened :false , category: [CategorySpecies.fishes, CategorySpecies.all] , description: "Elle ressemble à la crevette des marais Palaemonetes juvénile, que l'on rencontre en eau saumâtre. Les yeux sont bien développés et pigmentés.En fait, elle progresse grâce à des conditions climatiques en évolution : augmentation des températures et modification des cycles hydrologiques. C'est une espèce en extension d'aire : l'Homme lui facilite les choses avec la construction des canaux. Elle aime bien se mettre sous les péniches où elle broute les salissures, et voyage ainsi facilement en bateau-stop.", habitat: "il se situe en Amérique du Nord en Amérique du Sud et en Océanie ", biology:"Elle se nourrit de débris végétaux, de plantes aquatiques, de la couverture algale.", mainColor:[ColorChoice.grey, ColorChoice.white], secondaryColor: nil, bodyCover: BodyCover.carapace, minSize: 2 , maxSize: 4 , isShared:nil , isPin: false , isPin2: false, isPin3: true, localisation: [ EnumRegion.bretagne, EnumRegion.france]),
    
    
    
    //Mammiferes
    //12
    Species(picture: "herisson", picture2: nil, picture3: nil, name: "Hérisson d'Europe", latinName: "Pelophylax kl. esculentas", isProtected:false, isReglemented: false, isThreatened: false, category: [CategorySpecies.mammals, CategorySpecies.all], description: "C'est la plus grosse et la plus remarquable des musaraignes d'Europe. Elle mène une vie semi-aquatique dans les fleuves et les ruisseaux.", habitat: "animal semi-nocturne. Il chasse la nuit à la vitesse moyenne de 3 mètres par minute, mais peut faire des courtes pointes de vitesse10 et parcourt environ 2 ou 3 kilomètres[réf. nécessaire]. Dès le crépuscule, il cherche sa nourriture composée d'insectes, de vers, d'escargots, de limaces, d'œufs, de fruits et de baies. Il est à ce titre un auxiliaire de tout premier plan pour les jardiniers. Il s'attaque parfois aux serpents, lézards, rongeurs, batraciens, oiseaux nichant à terre. Il passe la journée à dormir (environ 18 heures par jour)", biology: " habite un terrier ou un tronc d'arbre, gîte qu'il aménage avec des feuilles, ou sous un buisson" , mainColor: [ColorChoice.brown], secondaryColor: [ColorChoice.black], bodyCover: BodyCover.épine, minSize: 20, maxSize: 30, isShared: nil, isPin: true, isPin2: true, isPin3: false, localisation: [EnumRegion.nord, EnumRegion.bretagne, EnumRegion.france, EnumRegion.iledeFrance]),
    //13
    Species(picture: "crossope", picture2: nil, picture3: nil, name: "Crossope aquatique", latinName: "Neomys fodiens", isProtected: true, isReglemented: true, isThreatened: false, category: [CategorySpecies.mammals, CategorySpecies.all], description: "La tête, dans le prolongement du corps, se termine par un museau pointu et un rhinarium qui lui permet de détecter la nourriture jusqu'à 3 cm dans le sol, grâce à un odorat très développé. Les oreilles sont courtes, 2 à 3 cm, et en partie cachées par les poils. Le Hérisson a quatre membres et une petite queue conique de 2 à 3 cm, mais il est assez rare de l'apercevoir6. Il possède trente-six dents.", habitat: "occupe les berges des cours d'eau et les plans d'eau riches en végétation. Il évolue parmi les racines, sous les branches ou dans les galeries qu'il creuse. En hiver, on peut le trouver dans les caves pleines d'eau.", biology: "sort régulièrement de son nid pour aller chercher sa nourriture dans l'eau, essentiellement des crustacés et d'autres animaux aquatiques, ainsi que des gastéropodes et des insectes. Elle capture aussi des proies plus grandes, comme des grenouilles ou des petits poissons." , mainColor: [ColorChoice.brown], secondaryColor: [ColorChoice.black], bodyCover: BodyCover.poil, minSize: 6, maxSize: 12, isShared: nil, isPin: false,isPin2: false,isPin3: true,localisation: [EnumRegion.nord, EnumRegion.bretagne, EnumRegion.france, EnumRegion.iledeFrance]),
    //14
    Species(picture: "daim", picture2: nil, picture3: nil, name: "Daim européen", latinName: "Dama dama", isProtected: false, isReglemented: true, isThreatened: false, category: [CategorySpecies.mammals, CategorySpecies.all], description: "Le daim européen (Dama dama) est un mammifère artiodactyle ruminant de la famille des cervidés, le mâle portant de grands bois plats et palmés.", habitat: "ils aiment les forêts mixtes ou claires de feuillus, les prairies arbustives ou rases, les montagnes basses et vallonnées où ils vivent en hardes de 6 à 50 individus dirigées par une vieille femelle.", biology: "se nourrit d'herbes, de pousses, de feuilles, de glands, de châtaignes mais également de fruits, de baies et bourgeons. L'hiver, il mange du lierre, des ronces, du gui, des écorces, des genêts et des graminées sèches (foin)." , mainColor: [ColorChoice.brown], secondaryColor: [ColorChoice.black, ColorChoice.white], bodyCover: BodyCover.poil, minSize: 85, maxSize: 120, isShared: nil, isPin: true,isPin2: false, isPin3: false,localisation: [EnumRegion.nord, EnumRegion.bretagne, EnumRegion.france, EnumRegion.iledeFrance]),
    
    
    //15
    //Reptiles et Amphibiens
    Species(picture: "la_grenouille_verte", picture2: nil, picture3: nil,  name: "Grenouille verte", latinName: "Pelophylax kl. esculentas", isProtected: true, isReglemented: true, isThreatened: false, category: [CategorySpecies.reptils, CategorySpecies.all], description: "La Grenouille verte ou la Grenouille comestible, est un amphibien qui résulte de l'hybridation entre les espèces suivantes : la Grenouille de Lessona, Pelophylax lessonae, et la Grenouille rieuse, Pelophylax ridibundus1,2. Cette grenouille présente un corps trapu, un museau fortement arrondi, une pupille horizontale ainsi que deux lignes de glandes bien marquées sur le dos. Le mâle possède deux sacs vocaux externes. Les palmures ne dépassent pas la moitié des orteils.", habitat: "plans d'eau, les marais, étangs, cours d'eau lents, forêts, prairies humides.", biology: "se nourrit d'arthropodes, d'insectes, de petits crustacés, de larves d'amphibiens, de vers." , mainColor: [ColorChoice.green], secondaryColor: [ColorChoice.brown], bodyCover: BodyCover.peau, minSize: 40, maxSize: 120, isShared: nil, isPin: true,isPin2: false, isPin3: false,localisation: [EnumRegion.nord,  EnumRegion.france]),
    
    //16
    Species(picture: "lezard_des_murailles",  picture2: nil, picture3: nil, name: "Lézard des murailles", latinName: "Podarcis muralis", isProtected: true, isReglemented: true, isThreatened: false, category: [CategorySpecies.reptils, CategorySpecies.all], description: "C'est un lézard de forme élancée, espèce extrêmement polymorphe, avec une variabilité extraordinaire de l'écaillure, une coloration très variable, brun, gris ou même verdâtre. La face ventrale est claire, jaune, bleu ou rougeâtre. La gorge est mouchetée de noir.", habitat: "vieux murs, tas de pierres, rochers, carrières, terrils, souches, apprécie spécialement les rails ou les quais de gares peu fréquentés. Ce lézard est beaucoup plus urbain que les autres espèces.", biology: "nourrit d'araignées, de lépidoptères, d'orthoptères, de vers de terre, de pucerons, de diptères (mouches), coléoptères et même d'hyménoptères.", mainColor: [ColorChoice.brown], secondaryColor: nil, bodyCover: BodyCover.peau, minSize: 18, maxSize: 25, isShared: nil, isPin: false,isPin2: false,isPin3: true, localisation: [EnumRegion.nord, EnumRegion.france]),
    
    //17
    Species(picture: "couleuvre_helvetique1", picture2: "couleuvre_helvetique2", picture3: "couleuvre_helvetique3", name: "Couleuvre helvétique", latinName: "Natrix helvetica", isProtected: true, isReglemented: true, isThreatened: false, category: [CategorySpecies.reptils, CategorySpecies.all], description: "Cette couleuvre, ovipare, est très semblable à Natrix natrix dont elle a été longtemps considérée comme une sous-espèce. Le « collier » est très marqué, aussi bien chez les jeunes que chez les adultes. Les barres transversales dorsales sont elles aussi bien visibles.Dans la nature elle semble s’hybrider avec Natrix natrix et Natrix maura", habitat: "tourbières plates, rives naturelles des étangs et des lacs, rivières, zones fluviales inondables, gravières, glaisières, clairières, lisières de forêts.", biology: " se nourrit de grenouilles, des crapauds, des tritons et des poissons, occasionnellement des lézards et des souris.", mainColor: [ColorChoice.brown, ColorChoice.grey], secondaryColor: [ColorChoice.red], bodyCover: BodyCover.peau, minSize: 20, maxSize: 140, isShared: nil, isPin: true,isPin2: false, isPin3: false,localisation: [EnumRegion.bretagne, EnumRegion.france]),
    
    
    //Insectes
    
    Species(picture: "punaise_verte", picture2: nil, picture3: nil, name: "Punaise verte", latinName: "Palomena prasina", isProtected: false, isReglemented: false, isThreatened: false, category: [CategorySpecies.insects, CategorySpecies.all], description: "Sa couleur verte tachetée de petits points noirs la rend très mimétique ; elle devient brune à l'approche de l'hiver mais redevient verte au retour du printemps. Les quatrièmes et cinquièmes segments antennaires sont rougeâtre et l'extrémité de ses ailes membraneuses est brune. À l'instar des insectes hémiptères, la punaise verte possède des pièces buccales spécialisées pour se nourrir de sève végétale", habitat:"milieux humides, des jardins aux forêts de feuillus. Au début de la saison des pluies, en automne, elle pénètre dans les habitations par les fenêtres ouvertes ou sous les toits pour rechercher un abri pour hiberner.", biology: "plante son appareil buccal dans le fruit et libère une enzyme digestive (amylase), apprécie particulièrement les pommiers et poiriers et certains herbacéss.", mainColor: [ColorChoice.green], secondaryColor: [ColorChoice.black], bodyCover: BodyCover.peau, minSize: 0.12, maxSize: 0.14, isShared: nil, isPin: true, isPin2: false, isPin3: false,localisation: [EnumRegion.nord, EnumRegion.bretagne, EnumRegion.france, EnumRegion.iledeFrance]),
    
    Species(picture: "azure_des_nerpruns", picture2: nil, picture3: nil, name: "Azuré des Nerpruns", latinName: "Celastrina argiolus", isProtected: false, isReglemented: false, isThreatened: false, category: [CategorySpecies.insects, CategorySpecies.all], description: "petit papillon au dessus bleu bordé d'une bordure gris-noir. Cette bordure est très fine et limitée à l'aile antérieure chez le mâle, et large chez la femelle. Le revers des ailes a un fond gris bleuté très pâle, orné de séries de petits points noirs, ceux de l'aile antérieure ayant la forme de tirets.", habitat:"La chenille est visible de mai à octobre, sur les fleurs, les fruits et les jeunes feuilles.L'espèce hiverne au stade de chrysalide, accrochée au-dessous d'une feuille", biology: "se nourrit essentiellement de miellat, mais descend volontiers butiner les Ronces et le Sureau yèble. Les chenilles dévorent les plantes hôtes.", mainColor: [ColorChoice.white], secondaryColor: [ColorChoice.black, ColorChoice.purple], bodyCover: nil, minSize: 0.23, maxSize: 0.30, isShared: nil, isPin: false, isPin2: false, isPin3: true,localisation: [EnumRegion.nord, EnumRegion.bretagne, EnumRegion.france, EnumRegion.iledeFrance]),
    
    Species(picture: "thecla_du_bouleau", picture2: nil, picture3: nil, name: "Thécla du Bouleau", latinName: "Thecla betulae", isProtected: false, isReglemented: false, isThreatened: false, category: [CategorySpecies.insects, CategorySpecies.all], description: " petit papillon qui présente un dimorphisme sexuel, le dessus du mâle est marron, celui de la femelle marron orné d'une grosse marque orange en croissant. Les deux présentent une queue orange aux postérieures. Le revers est de couleur jaune orné d'une bande orange limitée par une fine ligne blanche.", habitat:"Ses plantes hôtes sont le prunellier Prunus spinosa, ainsi que Prunus padus, Prunus domestica et d'autres rosacées", biology: "Les chenilles sont soignées par les fourmis Lasius niger.", mainColor: [ColorChoice.brown, ColorChoice.orange], secondaryColor: [ColorChoice.bronze], bodyCover: nil, minSize: nil, maxSize: nil, isShared: nil, isPin: false,isPin2: false,isPin3: true, localisation: [EnumRegion.nord, EnumRegion.bretagne, EnumRegion.france]),
     
    //Champignons
     Species(picture: "calocere", picture2: nil, picture3: nil, name: "Calocère visqueuse", latinName: "Calocera viscosa", isProtected: false, isReglemented: false, isThreatened: false, category: [CategorySpecies.mushroom, CategorySpecies.all], description: "La calocère visqueuse (Calocera viscosa) est une espèce de champignons de la famille des dacrymycètacées.Non comestible", habitat:"forestier, sur bois mort", biology: "Sporée jaune, sans anneau, odeaur légère et agréable.", mainColor: [ColorChoice.orange], secondaryColor:[ColorChoice.yellow], bodyCover: nil, minSize: 3, maxSize: 10, isShared: nil, isPin: true, isPin2: false, isPin3: false, localisation:  [EnumRegion.nord, EnumRegion.bretagne, EnumRegion.france]),
]



